#INTRO
#Set up is quick and easy. Simply replace any example text with your information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Condm Crew
org_summary:  >  # Enter your summary on the next line. Be sure to indent by two spaces.
  Hacemos videos pendejos con el Ãºnico objetivo de quitarte minutos de vida. ðŸ¤·â€â™‚ï¸ðŸ’   Y si, nuestro Ãºnico objetivo es ser una copia barata de la One Coin...


org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Somos una empresa, que nos dedicamos hacer videos producidos con la menor calidad posible y estamos buscando personas para introducirlos en el video y hacer el mejor entretenimiento con el menor presupuesto posible

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: Condmcrew@gmail.com
#org_street_address: . #Please include suite number on the line below
#org_address_suite: .
org_city: La Paz
org_state: Baja California Sur
#org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  
#org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  

#SOCIAL MEDIA
org_twitter_username: Condmcrew
#org_facebook_username: -----
org_instagram_username: Condmcrew

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
#fiscal_sponsor: false
#fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: one

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed
